# Generated by Django 3.0.4 on 2020-07-22 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gestion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OdpCriba',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('IN', 'Inicial'), ('AC', 'Aprobado Cliente'), ('AP', 'Aprobado Producción'), ('RN', 'Rizando'), ('TN', 'Tejiendo'), ('TR', 'Terminación'), ('FP', 'Falta pintura'), ('BO', 'Bodega'), ('DE', 'Despachado'), ('EE', 'Entregado')], default='IN', max_length=2)),
                ('fecha_aprobacion_produccion', models.DateField(auto_now_add=True)),
                ('numero_odp', models.IntegerField(default=None, null=True)),
                ('item', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion.ItemMallaCriba')),
            ],
        ),
        migrations.CreateModel(
            name='RolloCriba',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('peso_inicial', models.IntegerField()),
                ('peso_actual', models.IntegerField()),
                ('diametro', models.DecimalField(decimal_places=2, max_digits=4)),
                ('identificador', models.CharField(max_length=10)),
                ('material', models.CharField(choices=[('1018', 'Acero 1018'), ('1045', 'Acero 1045'), ('1070', 'Acero 1070')], max_length=10)),
                ('fecha_recibo', models.DateField(auto_now_add=True)),
                ('odp', models.ManyToManyField(blank=True, to='produccion.OdpCriba')),
            ],
            options={
                'ordering': ['-material'],
            },
        ),
    ]
